<?php
$z[0]=Array("arcurl","",33,48);
$z[1]=Array("title","",80,94);
$z[2]=Array("pubdate","",137,189);
$z[2][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[3]=Array("typeurl","",221,237);
$z[4]=Array("typename","",253,270);
$z[5]=Array("typename","",292,309);
$z[6]=Array("click","",342,356);
$z[7]=Array("arcurl","",376,391);
$z[8]=Array("title","",400,414);
$z[9]=Array("litpic","",468,483);
$z[10]=Array("title","",534,548);
$z[11]=Array("description","",574,624);
$z[11][4]['function']="cn_substr(@me,100)";

?>