<li>
              <div class="xiaopic"><a href="[field:arcurl/]" title="[field:title /]"  target="_blank"> <img src="[field:litpic/]" alt="[field:title /]" width="70" height="60"></a>
                <p><a href="[field:arcurl/]" title="[field:title /]" class="txt3" target="_blank" >[field:title /]</a></p>
                <span>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> </div>
            </li>