<?php
$z[0]=Array("arcurl","",33,48);
$z[1]=Array("title","",80,94);
$z[2]=Array("pubdate","",137,189);
$z[2][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[3]=Array("typeurl","",221,237);
$z[4]=Array("typename","",253,270);
$z[5]=Array("typename","",292,309);
$z[6]=Array("click","",357,371);
$z[7]=Array("arcurl","",407,422);
$z[8]=Array("title","",431,445);
$z[9]=Array("litpic","",499,514);
$z[10]=Array("title","",565,579);
$z[11]=Array("description","",605,655);
$z[11][4]['function']="cn_substr(@me,100)";

?>