<li>
              <h1><a href="[field:arcurl/]" target="_blank" class="txt4" >[field:title/]</a></h1>
              <span>发表于：[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span> <span>分类：<a href="[field:typeurl/]" title="查看 [field:typename/] 中的全部文章" >[field:typename/]</a></span> <span>浏览次数：
             [field:click/]
              次</span> <a href="[field:arcurl/]" title="[field:title/]" target="_blank"> <img width="575" height="255" src="[field:litpic/]" class="attachment-home-thumb wp-post-image" alt="[field:title/]"> </a>
              <p>[field:description function='cn_substr(@me,100)'/]…… </p>
            </li>