<?php
$z[0]=Array("flink","\r\n       <li>[field:link /]</li>\r\n       ",1083,1184);
$z[0][4]['titlelen']="50";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",1317,1349);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1462,1494);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1716,1748);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1829,1861);
$z[4][4]['name']="cfg_templets_skin";

?>