<?php
$z[0]=Array("flink","\r\n       <li>[field:link /]</li>\r\n       ",1079,1180);
$z[0][4]['titlelen']="50";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",1313,1345);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1460,1492);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1716,1748);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1831,1863);
$z[4][4]['name']="cfg_templets_skin";

?>